import Dashboardviews from "@/sections/dashboard/views/dashboardviews";
import React from "react";
export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};
const page = () => {
  return <Dashboardviews />;
};

export default page;
